---
grails:
    profile: web
    codegen:
        defaultPackage: com.spontorg
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

server:
   sessionTimeout: 7200  #seconds
---
grails:
    plugin:
        springsecurity:
            userLookup:
                userDomainClassName: com.spontorg.User
                authorityJoinClassName: com.spontorg.UserRole
            authority:
                className: com.spontorg.Role

            securityConfigType: InterceptUrlMap
            interceptUrlMap:
                - pattern: '/'
                  access:
                    - permitAll
                - pattern: '/**'
                  access:
                    - permitAll
            successHandler:
                defaultTargetUrl: '/hello/index'

            facebook:
                appId: '1603239159996051'
                secret: '4cb3c4818e496082f9625166041af2e4'
                domain:
                    classname: 'com.spontorg.FacebookUser'
                    appUserConnectionPropertyName: 'user'
                host: live.spontaneousorganization.com
                filter:
                    type: redirect
                permissions: ['email','public_profile','user_friends'] 
                rememberMe:
                    persistent: true
                    persistentToken:
                        domainClassName:'com.spontorg.PersistentLogin'
                roleHierarchyEntryClassName: 'com.spontorg.RoleHierarchyEntry'
                logout:
                     postOnly: false
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    databinding:
        dateFormats: ["dd/MM/yyyy HH:mm", "dd/MM/yyyy"]
    dbconsole:
        enabled: true
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

endpoints:
    jmx:
        unique-names: true

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
